---
apiVersion: apps/v1
#apiVersion: v1
kind: Deployment
metadata:
  name: rag-web-workload
  namespace: azure-iot-operations
  labels:
    app: rag-web-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-web-workload
  template:
    metadata:
      labels:
        app: rag-web-workload

    spec:
      imagePullSecrets:
         - name: <>

      containers:
        - name: rag-web
          image: <>
          imagePullPolicy: Always
          ports:  
          - containerPort: 8501
          env:
          - name: Login
            value: "True"
          
       
---
kind: Service
apiVersion: v1
metadata:
  name: rag-web-service
  namespace: azure-iot-operations
  labels:
    app: rag-web-workload
spec:
  selector:
    app: rag-web-workload
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
